<a href="https://colab.research.google.com/github/HasibullahAman/IBMAIEngineeringProfessionalCertificate/blob/Introduction-to-Deep-Learning-%26-Neural-Networks-with-Keras/Increase_the_number_of_hidden_layers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><span style="font-family:Comic Sans MS; color:navy "><h1>Task4</h1></span></center>

## Import library's

In [39]:
# i had just need this for preprocessing 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# I need this for my Neural network model
from keras.models import Sequential
from keras.layers import Dense
# for split data
from sklearn.model_selection import train_test_split
# for test our model
from sklearn.metrics import mean_squared_error

## Import Data

In [12]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

## Preprocessing & Normalization

In [14]:
concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

in the cell above I split the target and and my data, like the lab we have befor

In [33]:
predictors = (predictors - predictors.mean()) / predictors.std()
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

## Create a Neural Network

In [43]:
model = Sequential() # create a instance from sequential model
# Add a fully connected (Dense) layer with 10 units and ReLU activation
model.add(Dense(10,activation='relu'))
# add tow ohter layer in task 4
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(1)) # I got error and I add this layer ---> https://stackoverflow.com/questions/60988136/calculating-mean-square-error-return-y-true-and-y-pred-have-different-number-of
# Compile the model with binary mean_squerd_error and Adam optimizer
model.compile(loss='mean_squared_error',optimizer='adam')

In [44]:
X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=0)

In [45]:
model.fit(X_train, y_train, epochs=100) # in this notebook I have just change the number of epochs

Epoch 1/100
23/23 [==============================] - 1s 2ms/step - loss: 1563.4967
Epoch 2/100
23/23 [==============================] - 0s 2ms/step - loss: 1542.7043
Epoch 3/100
23/23 [==============================] - 0s 3ms/step - loss: 1511.0424
Epoch 4/100
23/23 [==============================] - 0s 2ms/step - loss: 1456.6167
Epoch 5/100
23/23 [==============================] - 0s 2ms/step - loss: 1360.4241
Epoch 6/100
23/23 [==============================] - 0s 2ms/step - loss: 1211.5298
Epoch 7/100
23/23 [==============================] - 0s 3ms/step - loss: 1005.5318
Epoch 8/100
23/23 [==============================] - 0s 3ms/step - loss: 784.6572
Epoch 9/100
23/23 [==============================] - 0s 2ms/step - loss: 610.0442
Epoch 10/100
23/23 [==============================] - 0s 2ms/step - loss: 506.9952
Epoch 11/100
23/23 [==============================] - 0s 2ms/step - loss: 437.6122
Epoch 12/100
23/23 [==============================] - 0s 3ms/step - loss: 385.4694
Epoch 13/100
23/23 [==============================] - 0s 2ms/step - loss: 342.9106
Epoch 14/100
23/23 [==============================] - 0s 2ms/step - loss: 308.4795
Epoch 15/100
23/23 [==============================] - 0s 2ms/step - loss: 279.4523
Epoch 16/100
23/23 [==============================] - 0s 2ms/step - loss: 257.1443
Epoch 17/100
23/23 [==============================] - 0s 2ms/step - loss: 236.6402
Epoch 18/100
23/23 [==============================] - 0s 2ms/step - loss: 221.3146
Epoch 19/100
23/23 [==============================] - 0s 2ms/step - loss: 207.4546
Epoch 20/100
23/23 [==============================] - 0s 2ms/step - loss: 196.3553
Epoch 21/100
23/23 [==============================] - 0s 2ms/step - loss: 187.2582
Epoch 22/100
23/23 [==============================] - 0s 2ms/step - loss: 180.9165
Epoch 23/100
23/23 [==============================] - 0s 2ms/step - loss: 174.2768
Epoch 24/100
23/23 [==============================] - 0s 3ms/step - loss: 169.2099
Epoch 25/100
23/23 [==============================] - 0s 2ms/step - loss: 164.1657
Epoch 26/100
23/23 [==============================] - 0s 2ms/step - loss: 160.9737
Epoch 27/100
23/23 [==============================] - 0s 3ms/step - loss: 157.6690
Epoch 28/100
23/23 [==============================] - 0s 2ms/step - loss: 155.4464
Epoch 29/100
23/23 [==============================] - 0s 3ms/step - loss: 153.5620
Epoch 30/100
23/23 [==============================] - 0s 2ms/step - loss: 150.2873
Epoch 31/100
23/23 [==============================] - 0s 2ms/step - loss: 148.5981
Epoch 32/100
23/23 [==============================] - 0s 2ms/step - loss: 146.9810
Epoch 33/100
23/23 [==============================] - 0s 2ms/step - loss: 144.8867
Epoch 34/100
23/23 [==============================] - 0s 2ms/step - loss: 143.2856
Epoch 35/100
23/23 [==============================] - 0s 2ms/step - loss: 141.6381
Epoch 36/100
23/23 [==============================] - 0s 3ms/step - loss: 140.2502
Epoch 37/100
23/23 [==============================] - 0s 2ms/step - loss: 138.6160
Epoch 38/100
23/23 [==============================] - 0s 2ms/step - loss: 136.9873
Epoch 39/100
23/23 [==============================] - 0s 2ms/step - loss: 136.1128
Epoch 40/100
23/23 [==============================] - 0s 2ms/step - loss: 134.5303
Epoch 41/100
23/23 [==============================] - 0s 2ms/step - loss: 132.8638
Epoch 42/100
23/23 [==============================] - 0s 2ms/step - loss: 131.4765
Epoch 43/100
23/23 [==============================] - 0s 2ms/step - loss: 129.8902
Epoch 44/100
23/23 [==============================] - 0s 2ms/step - loss: 128.7823
Epoch 45/100
23/23 [==============================] - 0s 2ms/step - loss: 127.0813
Epoch 46/100
23/23 [==============================] - 0s 3ms/step - loss: 126.0017
Epoch 47/100
23/23 [==============================] - 0s 3ms/step - loss: 124.6120
Epoch 48/100
23/23 [==============================] - 0s 2ms/step - loss: 123.3804
Epoch 49/100
23/23 [==============================] - 0s 2ms/step - loss: 122.3486
Epoch 50/100
23/23 [==============================] - 0s 2ms/step - loss: 120.9649
Epoch 51/100
23/23 [==============================] - 0s 2ms/step - loss: 119.6633
Epoch 52/100
23/23 [==============================] - 0s 2ms/step - loss: 118.6422
Epoch 53/100
23/23 [==============================] - 0s 2ms/step - loss: 117.0990
Epoch 54/100
23/23 [==============================] - 0s 2ms/step - loss: 116.2170
Epoch 55/100
23/23 [==============================] - 0s 3ms/step - loss: 114.3767
Epoch 56/100
23/23 [==============================] - 0s 3ms/step - loss: 113.2307
Epoch 57/100
23/23 [==============================] - 0s 3ms/step - loss: 112.2112
Epoch 58/100
23/23 [==============================] - 0s 2ms/step - loss: 110.5589
Epoch 59/100
23/23 [==============================] - 0s 2ms/step - loss: 109.2567
Epoch 60/100
23/23 [==============================] - 0s 2ms/step - loss: 107.9602
Epoch 61/100
23/23 [==============================] - 0s 2ms/step - loss: 106.5480
Epoch 62/100
23/23 [==============================] - 0s 3ms/step - loss: 105.1852
Epoch 63/100
23/23 [==============================] - 0s 2ms/step - loss: 103.9286
Epoch 64/100
23/23 [==============================] - 0s 3ms/step - loss: 102.9646
Epoch 65/100
23/23 [==============================] - 0s 3ms/step - loss: 101.1193
Epoch 66/100
23/23 [==============================] - 0s 2ms/step - loss: 100.1523
Epoch 67/100
23/23 [==============================] - 0s 2ms/step - loss: 98.7975
Epoch 68/100
23/23 [==============================] - 0s 2ms/step - loss: 97.7034
Epoch 69/100
23/23 [==============================] - 0s 2ms/step - loss: 96.3300
Epoch 70/100
23/23 [==============================] - 0s 2ms/step - loss: 95.0928
Epoch 71/100
23/23 [==============================] - 0s 2ms/step - loss: 93.6010
Epoch 72/100
23/23 [==============================] - 0s 2ms/step - loss: 92.6453
Epoch 73/100
23/23 [==============================] - 0s 2ms/step - loss: 91.2643
Epoch 74/100
23/23 [==============================] - 0s 2ms/step - loss: 90.7984
Epoch 75/100
23/23 [==============================] - 0s 2ms/step - loss: 88.9595
Epoch 76/100
23/23 [==============================] - 0s 3ms/step - loss: 87.9875
Epoch 77/100
23/23 [==============================] - 0s 2ms/step - loss: 86.7559
Epoch 78/100
23/23 [==============================] - 0s 3ms/step - loss: 85.8667
Epoch 79/100
23/23 [==============================] - 0s 2ms/step - loss: 84.8798
Epoch 80/100
23/23 [==============================] - 0s 3ms/step - loss: 84.1245
Epoch 81/100
23/23 [==============================] - 0s 2ms/step - loss: 83.3031
Epoch 82/100
23/23 [==============================] - 0s 2ms/step - loss: 82.0539
Epoch 83/100
23/23 [==============================] - 0s 4ms/step - loss: 81.4540
Epoch 84/100
23/23 [==============================] - 0s 4ms/step - loss: 80.4896
Epoch 85/100
23/23 [==============================] - 0s 5ms/step - loss: 79.3183
Epoch 86/100
23/23 [==============================] - 0s 4ms/step - loss: 78.5671
Epoch 87/100
23/23 [==============================] - 0s 4ms/step - loss: 77.9275
Epoch 88/100
23/23 [==============================] - 0s 4ms/step - loss: 77.0875
Epoch 89/100
23/23 [==============================] - 0s 3ms/step - loss: 76.6433
Epoch 90/100
23/23 [==============================] - 0s 5ms/step - loss: 75.4712
Epoch 91/100
23/23 [==============================] - 0s 4ms/step - loss: 75.0737
Epoch 92/100
23/23 [==============================] - 0s 4ms/step - loss: 74.8576
Epoch 93/100
23/23 [==============================] - 0s 4ms/step - loss: 73.9347
Epoch 94/100
23/23 [==============================] - 0s 3ms/step - loss: 73.1470
Epoch 95/100
23/23 [==============================] - 0s 3ms/step - loss: 72.5915
Epoch 96/100
23/23 [==============================] - 0s 4ms/step - loss: 71.9297
Epoch 97/100
23/23 [==============================] - 0s 4ms/step - loss: 71.6042
Epoch 98/100
23/23 [==============================] - 0s 4ms/step - loss: 70.8691
Epoch 99/100
23/23 [==============================] - 0s 4ms/step - loss: 70.6600
Epoch 100/100
23/23 [==============================] - 0s 3ms/step - loss: 70.0989

In [46]:
mse_list = []
for i in range(50):
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    mse_list.append(mse)

10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step

In [47]:
# Report the mean and standard deviation of the mean squared errors after we add tow other layer
print(np.mean(mse_list))
print(np.std(mse_list))

69.14700466892762
0.0