<a href="https://colab.research.google.com/github/HasibullahAman/IBMAIEngineeringProfessionalCertificate/blob/Introduction-to-Deep-Learning-%26-Neural-Networks-with-Keras/Increate_the_number_of_epochs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><span style="font-family:Comic Sans MS; color:navy "><h1>Task2</h1></span></center>

## Import library's

In [39]:
# i had just need this for preprocessing 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# I need this for my Neural network model
from keras.models import Sequential
from keras.layers import Dense
# for split data
from sklearn.model_selection import train_test_split
# for test our model
from sklearn.metrics import mean_squared_error

## Import Data

In [12]:
concrete_data = pd.read_csv('https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

## Preprocessing & Normalization

In [14]:
concrete_data_columns = concrete_data.columns
predictors = concrete_data[concrete_data_columns[concrete_data_columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

in the cell above I split the target and and my data, like the lab we have befor

In [33]:
predictors = (predictors - predictors.mean()) / predictors.std()
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

## Create a Neural Network

In [34]:
model = Sequential() # create a instance from sequential model
# Add a fully connected (Dense) layer with 10 units and ReLU activation
model.add(Dense(10,activation='relu'))
model.add(Dense(1)) # I got error and I add this layer ---> https://stackoverflow.com/questions/60988136/calculating-mean-square-error-return-y-true-and-y-pred-have-different-number-of
# Compile the model with binary mean_squerd_error and Adam optimizer
model.compile(loss='mean_squared_error',optimizer='adam')

In [35]:
X_train, X_test, y_train, y_test = train_test_split(predictors, target, test_size=0.3, random_state=0)

In [40]:
model.fit(X_train, y_train, epochs=100) # in this notebook I have just change the number of epochs

Epoch 1/100
23/23 [==============================] - 0s 11ms/step - loss: 311.1719
Epoch 2/100
23/23 [==============================] - 0s 8ms/step - loss: 301.0965
Epoch 3/100
23/23 [==============================] - 0s 6ms/step - loss: 291.5452
Epoch 4/100
23/23 [==============================] - 0s 6ms/step - loss: 282.7683
Epoch 5/100
23/23 [==============================] - 0s 6ms/step - loss: 274.8507
Epoch 6/100
23/23 [==============================] - 0s 6ms/step - loss: 267.3901
Epoch 7/100
23/23 [==============================] - 0s 6ms/step - loss: 260.7120
Epoch 8/100
23/23 [==============================] - 0s 5ms/step - loss: 254.3162
Epoch 9/100
23/23 [==============================] - 0s 7ms/step - loss: 248.7007
Epoch 10/100
23/23 [==============================] - 0s 3ms/step - loss: 243.3963
Epoch 11/100
23/23 [==============================] - 0s 2ms/step - loss: 238.5192
Epoch 12/100
23/23 [==============================] - 0s 2ms/step - loss: 234.2030
Epoch 13/100
23/23 [==============================] - 0s 3ms/step - loss: 230.0555
Epoch 14/100
23/23 [==============================] - 0s 2ms/step - loss: 226.6290
Epoch 15/100
23/23 [==============================] - 0s 2ms/step - loss: 223.1532
Epoch 16/100
23/23 [==============================] - 0s 2ms/step - loss: 220.1326
Epoch 17/100
23/23 [==============================] - 0s 2ms/step - loss: 217.4520
Epoch 18/100
23/23 [==============================] - 0s 2ms/step - loss: 214.8642
Epoch 19/100
23/23 [==============================] - 0s 2ms/step - loss: 212.5807
Epoch 20/100
23/23 [==============================] - 0s 2ms/step - loss: 210.3586
Epoch 21/100
23/23 [==============================] - 0s 2ms/step - loss: 208.3990
Epoch 22/100
23/23 [==============================] - 0s 2ms/step - loss: 206.4141
Epoch 23/100
23/23 [==============================] - 0s 2ms/step - loss: 204.7153
Epoch 24/100
23/23 [==============================] - 0s 2ms/step - loss: 203.1191
Epoch 25/100
23/23 [==============================] - 0s 2ms/step - loss: 201.5450
Epoch 26/100
23/23 [==============================] - 0s 2ms/step - loss: 200.0348
Epoch 27/100
23/23 [==============================] - 0s 2ms/step - loss: 198.6157
Epoch 28/100
23/23 [==============================] - 0s 2ms/step - loss: 197.2750
Epoch 29/100
23/23 [==============================] - 0s 3ms/step - loss: 195.9907
Epoch 30/100
23/23 [==============================] - 0s 2ms/step - loss: 194.6542
Epoch 31/100
23/23 [==============================] - 0s 2ms/step - loss: 193.4620
Epoch 32/100
23/23 [==============================] - 0s 2ms/step - loss: 192.2845
Epoch 33/100
23/23 [==============================] - 0s 2ms/step - loss: 191.1300
Epoch 34/100
23/23 [==============================] - 0s 2ms/step - loss: 189.9892
Epoch 35/100
23/23 [==============================] - 0s 2ms/step - loss: 188.8039
Epoch 36/100
23/23 [==============================] - 0s 2ms/step - loss: 187.7508
Epoch 37/100
23/23 [==============================] - 0s 2ms/step - loss: 186.6439
Epoch 38/100
23/23 [==============================] - 0s 2ms/step - loss: 185.5945
Epoch 39/100
23/23 [==============================] - 0s 2ms/step - loss: 184.5356
Epoch 40/100
23/23 [==============================] - 0s 2ms/step - loss: 183.5562
Epoch 41/100
23/23 [==============================] - 0s 2ms/step - loss: 182.4589
Epoch 42/100
23/23 [==============================] - 0s 2ms/step - loss: 181.5235
Epoch 43/100
23/23 [==============================] - 0s 2ms/step - loss: 180.4366
Epoch 44/100
23/23 [==============================] - 0s 2ms/step - loss: 179.4770
Epoch 45/100
23/23 [==============================] - 0s 2ms/step - loss: 178.5938
Epoch 46/100
23/23 [==============================] - 0s 2ms/step - loss: 177.7008
Epoch 47/100
23/23 [==============================] - 0s 2ms/step - loss: 176.7806
Epoch 48/100
23/23 [==============================] - 0s 2ms/step - loss: 175.9413
Epoch 49/100
23/23 [==============================] - 0s 2ms/step - loss: 175.0689
Epoch 50/100
23/23 [==============================] - 0s 2ms/step - loss: 174.2240
Epoch 51/100
23/23 [==============================] - 0s 2ms/step - loss: 173.3230
Epoch 52/100
23/23 [==============================] - 0s 2ms/step - loss: 172.4956
Epoch 53/100
23/23 [==============================] - 0s 2ms/step - loss: 171.7308
Epoch 54/100
23/23 [==============================] - 0s 2ms/step - loss: 170.7896
Epoch 55/100
23/23 [==============================] - 0s 2ms/step - loss: 170.0306
Epoch 56/100
23/23 [==============================] - 0s 2ms/step - loss: 169.2097
Epoch 57/100
23/23 [==============================] - 0s 2ms/step - loss: 168.3098
Epoch 58/100
23/23 [==============================] - 0s 2ms/step - loss: 167.5668
Epoch 59/100
23/23 [==============================] - 0s 2ms/step - loss: 166.7722
Epoch 60/100
23/23 [==============================] - 0s 2ms/step - loss: 165.8865
Epoch 61/100
23/23 [==============================] - 0s 2ms/step - loss: 165.0836
Epoch 62/100
23/23 [==============================] - 0s 2ms/step - loss: 164.3710
Epoch 63/100
23/23 [==============================] - 0s 2ms/step - loss: 163.5633
Epoch 64/100
23/23 [==============================] - 0s 2ms/step - loss: 162.7902
Epoch 65/100
23/23 [==============================] - 0s 2ms/step - loss: 162.0744
Epoch 66/100
23/23 [==============================] - 0s 2ms/step - loss: 161.2961
Epoch 67/100
23/23 [==============================] - 0s 2ms/step - loss: 160.5868
Epoch 68/100
23/23 [==============================] - 0s 2ms/step - loss: 159.8306
Epoch 69/100
23/23 [==============================] - 0s 2ms/step - loss: 159.0703
Epoch 70/100
23/23 [==============================] - 0s 3ms/step - loss: 158.3166
Epoch 71/100
23/23 [==============================] - 0s 2ms/step - loss: 157.6741
Epoch 72/100
23/23 [==============================] - 0s 2ms/step - loss: 156.8329
Epoch 73/100
23/23 [==============================] - 0s 2ms/step - loss: 156.0409
Epoch 74/100
23/23 [==============================] - 0s 2ms/step - loss: 155.3396
Epoch 75/100
23/23 [==============================] - 0s 2ms/step - loss: 154.5578
Epoch 76/100
23/23 [==============================] - 0s 2ms/step - loss: 153.8863
Epoch 77/100
23/23 [==============================] - 0s 2ms/step - loss: 153.1088
Epoch 78/100
23/23 [==============================] - 0s 2ms/step - loss: 152.4354
Epoch 79/100
23/23 [==============================] - 0s 2ms/step - loss: 151.6027
Epoch 80/100
23/23 [==============================] - 0s 2ms/step - loss: 150.9457
Epoch 81/100
23/23 [==============================] - 0s 2ms/step - loss: 150.1653
Epoch 82/100
23/23 [==============================] - 0s 2ms/step - loss: 149.3536
Epoch 83/100
23/23 [==============================] - 0s 2ms/step - loss: 148.5778
Epoch 84/100
23/23 [==============================] - 0s 2ms/step - loss: 147.7847
Epoch 85/100
23/23 [==============================] - 0s 2ms/step - loss: 147.0015
Epoch 86/100
23/23 [==============================] - 0s 2ms/step - loss: 146.2265
Epoch 87/100
23/23 [==============================] - 0s 2ms/step - loss: 145.2745
Epoch 88/100
23/23 [==============================] - 0s 2ms/step - loss: 144.4172
Epoch 89/100
23/23 [==============================] - 0s 2ms/step - loss: 143.5263
Epoch 90/100
23/23 [==============================] - 0s 2ms/step - loss: 142.6354
Epoch 91/100
23/23 [==============================] - 0s 2ms/step - loss: 141.7401
Epoch 92/100
23/23 [==============================] - 0s 2ms/step - loss: 140.9291
Epoch 93/100
23/23 [==============================] - 0s 2ms/step - loss: 140.0840
Epoch 94/100
23/23 [==============================] - 0s 2ms/step - loss: 139.1558
Epoch 95/100
23/23 [==============================] - 0s 2ms/step - loss: 138.3026
Epoch 96/100
23/23 [==============================] - 0s 2ms/step - loss: 137.4029
Epoch 97/100
23/23 [==============================] - 0s 2ms/step - loss: 136.6192
Epoch 98/100
23/23 [==============================] - 0s 2ms/step - loss: 135.7701
Epoch 99/100
23/23 [==============================] - 0s 2ms/step - loss: 134.9143
Epoch 100/100
23/23 [==============================] - 0s 2ms/step - loss: 133.9919

In [41]:
mse_list = []
for i in range(50):
    y_pred = model.predict(X_test)
    mse = mean_squared_error(y_test, y_pred)
    mse_list.append(mse)

10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 3ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step
10/10 [==============================] - 0s 2ms/step

In [42]:
# Report the mean and standard deviation of the mean squared errors
print(np.mean(mse_list))
print(np.std(mse_list))

122.95844634527772
1.4210854715202004e-14